modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="cm" #mandatory

version="1.0" #mandatory

displayName="inconspicuousLiquidMod" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://www.dafk.net/what/" #optional

logoFile="examplemod.png" #optional

credits="Thanks to TurtyWurty and the whole server for the idea" #optional

authors="Me and TurtyWurty for moral support" #optional

description='''
A great mod that adds a inconspicuousLiquid that can be made into lots of tools and 
	
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.cm]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.cm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
